//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarServiceManagementSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BookAMechanicEntities : DbContext
    {
        public BookAMechanicEntities()
            : base("name=BookAMechanicEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tbl_customer> tbl_customer { get; set; }
        public DbSet<tbl_mechanic> tbl_mechanic { get; set; }
        public DbSet<tbl_admin> tbl_admin { get; set; }
        public DbSet<tbl_cancel> tbl_cancel { get; set; }
        public DbSet<tbl_completed> tbl_completed { get; set; }
        public DbSet<tbl_order> tbl_order { get; set; }
    }
}
