//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarServiceManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_completed
    {
        public int id { get; set; }
        public int order_id { get; set; }
        public string customer_review { get; set; }
        public string mechanic_review { get; set; }
        public int client_rating { get; set; }
        public int mechanic_rating { get; set; }
        public System.DateTime complete_date { get; set; }
        public int client_id { get; set; }
        public int mechanic_id { get; set; }
    
        public virtual tbl_customer tbl_customer { get; set; }
        public virtual tbl_mechanic tbl_mechanic { get; set; }
        public virtual tbl_order tbl_order { get; set; }
    }
}
